/*
   -- Double_Joystick_Drive_1 --
   
   To compile this code using RemoteXY library 4.1.4 or later version 
   download by link http://remotexy.com/en/library/
   To connect using RemoteXY mobile app by link http://remotexy.com/en/download/                   
     - for ANDROID 4.16.02 or later version;
     - for iOS 1.13.1 or later version;
    
   To interact with the GUI, please refer to the manual: 
   https://remotexy.com/ru/help/code/interaction/

   This source code was automatically generated by the RemoteXY editor and 
   is an example for the RemoteXY library. 
   Licensed under the MIT License. See the LICENSE file in the RemoteXY library
   root (https://github.com/RemoteXY/RemoteXY-Arduino-library) for full license 
   details.             
*/

//////////////////////////////////////////////
//        RemoteXY include library          //
//////////////////////////////////////////////

// you can enable debug logging to Serial at 115200
//#define REMOTEXY__DEBUGLOG    

// RemoteXY select connection mode and include library 
#define REMOTEXY_MODE__ESP32CORE_BLE

#include <BLEDevice.h>

// RemoteXY connection settings 
#define REMOTEXY_BLUETOOTH_NAME "RemoteXY"


#include <RemoteXY.h>

// RemoteXY GUI configuration  
#pragma pack(push, 1)  
uint8_t RemoteXY_CONF[] =   // 95 bytes
  { 255,5,0,0,0,88,0,19,0,0,0,0,0,2,106,200,200,84,1,1,
  5,0,5,14,29,143,143,12,18,53,53,32,2,26,31,5,226,40,143,143,
  133,19,54,54,32,2,26,31,129,241,12,71,29,35,6,8,12,64,17,89,
  0,129,13,19,18,29,156,7,8,12,64,17,88,0,2,41,29,23,52,85,
  7,30,13,0,2,26,31,31,79,78,0,79,70,70,0 };
  
// this structure defines all the variables and events of your control interface 
struct {

    // input variables
  int8_t joystick_01_x_IGNORE; // from -100 to 100
  int8_t joystick_01_y; // from -100 to 100
  int8_t joystick_02_x; // from -100 to 100
  int8_t joystick_02_y_IGNORE; // from -100 to 100
  uint8_t switch_01; // =1 if switch ON and =0 if OFF, from 0 to 1

    // other variable
  uint8_t connect_flag;  // =1 if wire connected, else =0

} RemoteXY;   
#pragma pack(pop)
 
/////////////////////////////////////////////
//           END RemoteXY include          //
/////////////////////////////////////////////

#define PIN_BUTTON_01 27

// Left motor
#define PIN_RM_DIR1 13    //IN1  //right motor forward
#define PIN_RM_DIR2 12    //IN2  //right motor backward
#define PIN_RM_SPEED 14   //ENA  //right motor speed
// Right motor
#define PIN_LM_DIR1 27    //IN3  //left motor forward
#define PIN_LM_DIR2 26    //IN4  //left motor backward
#define PIN_LM_SPEED 25   //ENB  //left motor speed

void setup() 
{
  Serial.begin(115200);
  RemoteXY_Init (); 
  //pinMode (PIN_BUTTON_01, OUTPUT);
  // Right motor
  pinMode (PIN_RM_DIR1, OUTPUT);
  pinMode (PIN_RM_DIR2, OUTPUT);
  pinMode (PIN_RM_SPEED, OUTPUT);
  // Left motor
  pinMode (PIN_LM_DIR1, OUTPUT);
  pinMode (PIN_LM_DIR2, OUTPUT);
  pinMode (PIN_LM_SPEED, OUTPUT);
}

void loop() 
{ 
  RemoteXY_Handler ();

  if(RemoteXY.switch_01 == 0 ? LOW : HIGH)
    adjustMotor_joystick(PIN_LM_SPEED, PIN_RM_SPEED, RemoteXY.joystick_01_y, RemoteXY.joystick_02_x, PIN_RM_DIR1, PIN_RM_DIR2, PIN_LM_DIR1, PIN_LM_DIR2);
}

void adjustMotor_joystick(int pinL, int pinR, int8_t speed, int8_t direction, int dirPinRM1, int dirPinRM2, int dirPinLM1, int dirPinLM2) {
    int rmSpeed = sliderToMotorSpeed_FIXED(speed);
    int lmSpeed = sliderToMotorSpeed_FIXED(speed);
    
    /* FORWARDS & BACKWARDS */
    if (speed<0) {        // forward
      FORWARD_M(dirPinRM1, dirPinRM2);
      FORWARD_M(dirPinLM1, dirPinLM2);
    } else if (speed>0) { // reverse 
      REVERSE_M(dirPinRM1, dirPinRM2); 
      REVERSE_M(dirPinLM1, dirPinLM2); 
    } 

    /* LEFT & RIGHT */
    // Calculates turn speed change
    int changeTurnSpeed = 0;
    if ( abs(direction) > 25) 
      changeTurnSpeed = 75;
    if ( abs(direction) > 75) 
      changeTurnSpeed = 150;
    // Applies it to correct direction
    if (direction > 0) // turn right
      rmSpeed = constrain(rmSpeed - changeTurnSpeed, 0, 255);
    else if (direction < 0) // turn left
      lmSpeed = constrain(lmSpeed - changeTurnSpeed, 0, 255);
    
    Serial.print(rmSpeed);
    Serial.print("\t");
    Serial.println(lmSpeed);

    // Adjust motor speeds
    analogWrite(pinR, rmSpeed);
    analogWrite(pinL, lmSpeed);
}

/////////////////////////////////////////////
//           MOTOR CONTROLLS               //
/////////////////////////////////////////////

void adjustMotor_slider(int pin, int8_t speed, int dirPin1, int dirPin2) {
  // motor speed
  analogWrite( pin, sliderToMotorSpeed_FIXED(speed) );
  // forward
  if (speed>50) {
    FORWARD_M(dirPin1, dirPin2); // direction pins
  } 
  // reverse
  else if (speed<50) {
    REVERSE_M(dirPin1, dirPin2); // direction pins
  } 
}

#define ZERO  0 // Zero position on the slider
#define MAX_THRES   75  // Thresholds relative to the defined zero position
#define MID_THRES   25 
#define MAX_SPEED   255 // Speeds (in 0 - 255)
#define MID_SPEED   200
int sliderToMotorSpeed_FIXED(int8_t speed) {
  const int zeroedSpeed = abs(speed - ZERO);
  if ( zeroedSpeed > MAX_THRES) 
    return MAX_SPEED;
  else if (zeroedSpeed > MID_THRES)
    return MID_SPEED;
  else
    return 0;
}

int sliderToMotorSpeed_LINEAR(int8_t speed) {
  return map(speed, 0, 100, 0, 255);
}

void FORWARD_M(int dirPin1, int dirPin2) {
  digitalWrite(dirPin1, HIGH);
  digitalWrite(dirPin2, LOW);
}

void REVERSE_M(int dirPin1, int dirPin2) {
  digitalWrite(dirPin1, LOW);
  digitalWrite(dirPin2, HIGH);
}

void STOP_M(int dirPin1, int dirPin2) {
  digitalWrite(dirPin1, LOW);
  digitalWrite(dirPin2, LOW);
}